language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: cv0gyEkrUhUDnE85qAxPaHF7BtX0biM6kxAzuxaCUrWw9mvCIQQZQTF68oMhIkY5wEVtC4ENC785M2Cek05RsIkomQ7xy+S7HZoSlHUMgAJgHCqUdVa10hYiVoHcEyVfySPlyA7rT4DCuyFCJMOkQUzClJMpQIaUBz5do70XZVIryLGNWsHOuWS3AAw9WPEkjB6Zthd8chJb5lRhLKTWuEGTPqbFRPBT4JU5RAd+FOHFvuzGZ6QDRRkJoScpOF7wQ2kiTVlbW4aRNMWiVMgYdiuokbDYPN+1WVFZykNGtLx3IQdmk68gRveaiZ3iyivLp9SLZ0Q2oa0WxUnCjDFsq8RI9oD2vfldnTg4kN7SlWvieGv3Qovx0EdP2ON6g9o6+bI9yw1zeiFETA2suMQj2uUu4BKhMApqJ8hYB0mRMkVzZPdOS1jqcXgAK6XVSvFn5/3gOHOz/hBrbJ7LTx9fytHGUvFBwtiH1/u1rod7A0kEKLGbZAVp26dNA2FNBJzheaN5qK0GOsgylIZ/LMYmOE38qZXLVxQOh5RAbMOa1xjbuFX7fp0sPEvnjaGgJ5cJs8F2uWwaul7xyG/3Gk7xQxHSFmT0FBxh3bLpLk1AlzMQgVk2U3IIj16XxiOEt12y6jZ+4LZEkC5RyZC8WD0ngA0J661f6s2MtezXB+oN4qI=
app: mysterious-cove-79333
  on:
    repo: pantur/scot_free_bot
script:
- echo "=== skipping tests ==="
