language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: AKeg7d/e2CbHXyYmmsy0R5SELqwu2QidPq+Sk+CD3fvKCYEvR42RZ1QxIuFpluXzWqRRXeU3Jg1xOenVVJ8vMc1q9D1uj7AdYypNDvEFLX9ENl5dN96WzAJcPeEEZOB1MwpYdtAhHzsr1V8S3ZHxApwxPhRc+7iovUwW6eD8TknkAckjgwb1BP4mtmhC5AdUWyg2ml8w8yPoX1+H0Is7TEDePbw74DM26IMUk+o8677F/iphR6dHTHsPoWhUIjTvsCAuxXx1MhSGseuaiuNWy+Y9FOyzCNuS8tlHzvYJtJkZkXlG8rBtgqngAD7GkRN33kp3wHEHQ1FU0l1xSLqVvetx3CQftlj9TWZD5Tx3aNUhyusYJ/LMD7Pgqteg5Awr+zsmBpzJhvNgGU7iy24seuOy1lSg268+6IaZI/eQFs4XzfnUsj1BQkJieA9qa5m++ExLn+c4By8lAopAnsZFMPlDH6EIHO9cGfaEEVCKMcCOQN+osHCOrE2L+q+UgGu+cRg/oXPJyIDf4YtYhnoY4cPB5aE18OocwJWFE1aTct5dZN8BO1tiQXsebQeYd87vQMQfwEt7a4DqXZ7SEdGcZXwJkSGI6NkAs92ZqhM+qJnH99tPtynHnsqikWUDQXRozHW3/WOObwIzdJQk7AQeV0tLn6ImgSwfjUcG683HTfw=
  app: scot_free_bot
  on:
    repo: pantur/scot_free_bot
script: 
- echo "skipping tests"
